package agent

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/b070nd/stAirCase/src/internal/orchestrator"
	"github.com/b070nd/stAirCase/src/internal/sandbox"
)

// OpenCode runs OpenCode (`opencode run`) in the run's worktree as the run's
// agent, built from its documentation (opencode.ai/docs/plugins): a plugin
// generated for the run hooks tool.execute.before, posts every tool call to
// the run and throws to block it, so edits, patches and commands are decided
// before they run and every other tool is refused.
//
// OpenCode cannot be told to ignore plugins of the user or the repository, and
// a plugin that fails to load lets calls through; so a session whose plugin
// never reaches the run fails, and finalize refuses any change nobody approved.
type OpenCode struct {
	Prompt  string
	Model   string // optional --model provider/model
	Bin     string // default "opencode"
	HookBin string // unused; the plugin talks to the run itself
}

// opencodeRules tell the model how the governed session works.
const opencodeRules = `Make file changes with edit, write or apply_patch: each one is reviewed before it is applied. ` +
	`Only files inside the project can be read or changed.`

// Run starts the hook endpoint, then OpenCode, and waits for it.
func (o *OpenCode) Run(ctx context.Context, env *orchestrator.AgentEnv) error {
	root, err := filepath.EvalSymlinks(env.Worktree)
	if err != nil {
		return err
	}
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return err
	}
	h := &hookServer{env: env, root: root, token: rand.Text(), pending: map[string]orchestrator.Approval{}, calls: map[string]*hookCall{},
		name: "opencode", label: "OpenCode", norm: opencodeInput}
	srv := &http.Server{Handler: h, ReadHeaderTimeout: 10 * time.Second}
	go func() { _ = srv.Serve(ln) }()
	defer func() { _ = srv.Close() }()

	dir, err := os.MkdirTemp("", "staircase-opencode-") // outside the worktree
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(dir) }()
	session, _ := json.Marshal(map[string]string{"url": "http://" + ln.Addr().String() + "/hook", "token": h.token})
	hookFile := filepath.Join(dir, "hook.json")
	if err := os.WriteFile(hookFile, session, 0o600); err != nil {
		return err
	}
	plugins := filepath.Join(dir, "config", "plugins")
	if err := os.MkdirAll(plugins, 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(plugins, "staircase.js"), OpenCodePlugin(hookFile), 0o600); err != nil {
		return err
	}
	// OpenCode must not stop to ask: stAirCase's plugin decides. It may not
	// leave the project or loop, and gets no sharing or self-update.
	cfg, _ := json.Marshal(map[string]any{
		"permission": map[string]string{"*": "allow", "external_directory": "deny", "doom_loop": "deny"},
		"share":      "disabled", "autoupdate": false})

	args := []string{"run", o.Prompt + "\n\n" + opencodeRules}
	if o.Model != "" {
		args = append(args, "--model", o.Model)
	}
	cmd := exec.CommandContext(ctx, orDefault(o.Bin, "opencode"), args...)
	// The user's global config and plugins are not read (XDG_CONFIG_HOME is an
	// empty folder); its login (in the data folder) is.
	cmd.Dir, cmd.Env = root, append(sandbox.Env(), HookFileEnv+"="+hookFile,
		"OPENCODE_CONFIG_DIR="+filepath.Join(dir, "config"), "OPENCODE_CONFIG_CONTENT="+string(cfg),
		"XDG_CONFIG_HOME="+filepath.Join(dir, "xdg"), "OPENCODE_DISABLE_AUTOUPDATE=true")
	cmd.WaitDelay = 5 * time.Second
	sandbox.KillGroup(cmd)
	var stdout bytes.Buffer
	stderr := &tail{max: 4096}
	cmd.Stdout, cmd.Stderr = &stdout, stderr
	runErr := cmd.Run()
	env.Emit(ctx, orchestrator.Usage{Agent: "opencode", Model: orDefault(o.Model, "opencode"), Content: preview(stdout.String())})
	switch {
	case runErr != nil:
		return fmt.Errorf("opencode: %w: %s%s", runErr, preview(stdout.String()), stderr)
	case !h.started.Load():
		return errors.New("opencode never ran staircase's hooks, so the session was not governed; nothing it did is kept")
	}
	return nil
}

// OpenCodePlugin is the plugin that routes OpenCode's tool calls through the
// run whose session file is sessionFile. Any failure throws, which blocks the
// call: nothing is swallowed.
func OpenCodePlugin(sessionFile string) []byte {
	file, _ := json.Marshal(sessionFile)
	return fmt.Appendf(nil, `// Generated by staircase for one governed run: every tool call is decided by it.
import fs from "node:fs"

const SESSION = %s

const call = async (body) => {
  const s = JSON.parse(fs.readFileSync(SESSION, "utf8"))
  const r = await fetch(s.url, {
    method: "POST",
    headers: { Authorization: "Bearer " + s.token, "Content-Type": "application/json" },
    body: JSON.stringify(body),
  })
  if (!r.ok) throw new Error("staircase: the run answered " + r.status)
  return await r.json()
}

export const Staircase = async () => {
  await call({ hook_event_name: "SessionStart" })
  return {
    "tool.execute.before": async (input, output) => {
      const a = await call({ hook_event_name: "PreToolUse", tool_name: input.tool, tool_input: output.args, tool_use_id: input.callID })
      const d = a && a.hookSpecificOutput
      if (!d || d.permissionDecision !== "allow") throw new Error((d && d.permissionDecisionReason) || "staircase: refused")
    },
    "tool.execute.after": async (input, output) => {
      const a = await call({ hook_event_name: "PostToolUse", tool_name: input.tool, tool_input: input.args, tool_use_id: input.callID })
      if (a && a.decision === "block") throw new Error(a.reason || "staircase: refused")
    },
  }
}
`, file)
}

// opencodeInput puts an OpenCode tool call in Claude Code's shape: its tools
// and arguments are named as Claude Code's (edit is Edit with oldString,
// newString and replaceAll, write is Write, read is Read, bash is Bash) and
// apply_patch keeps its name with the patch as its command, for the patch
// parser. Tools with no counterpart keep their name and are refused.
func opencodeInput(in hookInput) hookInput {
	tool, ok := map[string]string{"edit": "Edit", "write": "Write", "read": "Read", "glob": "Glob", "grep": "Grep",
		"bash": "Bash", "todowrite": "TodoWrite", "apply_patch": "apply_patch"}[in.Tool]
	if !ok {
		return in
	}
	var args map[string]any
	if json.Unmarshal(in.Input, &args) != nil {
		return in
	}
	if conflict := aliasArgs(args, map[string]string{"filePath": "file_path", "oldString": "old_string", "newString": "new_string",
		"replaceAll": "replace_all", "patchText": "command"}); conflict != "" {
		return refuseAmbiguous(in, conflict)
	}
	in.Tool = tool
	in.Input, _ = json.Marshal(args)
	return in
}
